---
kind: pipeline
type: docker
name: default

steps:
- name: dspace-cris-ci
  image: maven:3.6.3-jdk-11
  environment:
    MAVEN_OPTS: -Xmx1024M
    submission__P__lookup__P__ads__P__apikey:
      from_secret: ADS_APIKEY
    submission__P__lookup__P__epo__P__consumerKey:
      from_secret: EPO_APIKEY
    submission__P__lookup__P__epo__P__consumerSecretKey:
      from_secret: EPO_APISECRET
  commands:         
  - ./dspace-api/src/test/data/dspaceFolder/bin/install_grobid.sh
  - mvn clean install license:check -DskipTests=false -DskipITs=false -Pdspace-rest -P !assembly -B -V -Dsurefire.rerunFailingTestsCount=2
